// config/client.ts
// ============================================================================
// CLIENT CONFIGURATION - Auto-generated by Setup Wizard
// ============================================================================

export const clientConfig = {
  // ==========================================================================
  // PLATFORM TYPE
  // ==========================================================================
  platformType: "founder_service_provider" as 'impact_investor' | 'commercial_investor' | 'family_office' | 'founder_service_provider',
  platformMode: "screening" as 'screening' | 'coaching',

  // ==========================================================================
  // COMPANY INFORMATION
  // ==========================================================================
  company: {
    name: "Corporate AI Solutions",
    legalName: "Corporate AI Solutions",
    tagline: "Corporate AI Solutions provides white-label AI platforms to turn cold pitch emails and calls into qualified deal flow for businesses.",
    description: "Corporate AI Solutions provides white-label AI platforms to turn cold pitch emails and calls into qualified deal flow for businesses.",
    website: "https://corporateaisolutions.com/raiseready-white-label/",
    platformUrl: "",
    supportEmail: "dennis@corporateaisolutions.com",
    salesEmail: "dennis@corporateaisolutions.com",
    social: {
      linkedin: "",
      twitter: "",
      youtube: "",
    },
    logo: {
      light: "/logo-light.svg",
      dark: "/logo-dark.svg",
      favicon: "/favicon.ico",
    },
  },

  // ==========================================================================
  // ADMIN USER
  // ==========================================================================
  admin: {
    firstName: "Dennis",
    lastName: "McMahon",
    email: "dennis@corporateaisolutions.com",
    phone: "",
    position: "CEO",
    linkedIn: "",
  },

  // ==========================================================================
  // OFFICE LOCATIONS
  // ==========================================================================
  offices: [
    {
      city: "Brisbane",
      country: "Australia",
      address: "Brisbane, Queensland",
      phone: "",
      isPrimary: true,
    },
  ],

  // ==========================================================================
  // THEME & BRANDING
  // ==========================================================================
  theme: {
    mode: "dark" as "dark" | "light",
    colors: {
      primary: "#4285f4",
      primaryHover: "#4285f4",
      accent: "#6c9eff",
      accentHover: "#6c9eff",
      background: "#ffffff",
      surface: "#1E293B",
      text: "#333333",
      textMuted: "#94A3B8",
      border: "#334155",
      gradient: { from: "#4285f4", via: "#ffffff", to: "#6c9eff" },
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
    },
    gradients: {
      hero: "from-purple-600 via-violet-700 to-indigo-800",
      button: "from-purple-500 to-violet-600",
      card: "from-slate-800 to-slate-900",
    },
    fonts: {
      heading: "Inter",
      body: "Inter",
    },
    borderRadius: "0.5rem",
  },

  // ==========================================================================
  // LANDING PAGE CONTENT
  // ==========================================================================
  landing: {
    hero: {
      headline: "Perfect Your Pitch with Corporate AI Solutions",
      subHeadline: "Corporate AI Solutions provides white-label AI platforms to turn cold pitch emails and calls into qualified deal flow for businesses.",
      ctaText: "Start Your Pitch",
      ctaLink: "/signup/founder",
      secondaryCtaText: "For Investors",
      secondaryCtaLink: "/signup/investor",
    },
    stats: [
      { value: "500+", label: "Founders Coached" },
      { value: "$50M+", label: "Capital Raised" },
      { value: "85%", label: "Pitch Improvement" },
      { value: "24h", label: "Response Time" },
    ],
    valueProps: [
      {
        icon: "Brain",
        title: "AI Pitch Analysis",
        description: "Get instant feedback on your pitch deck from our AI coaching system.",
      },
      {
        icon: "Target",
        title: "Investor Alignment",
        description: "Match with investors whose thesis aligns with your business.",
      },
      {
        icon: "TrendingUp",
        title: "Track Progress",
        description: "Watch your pitch scores improve over time with actionable insights.",
      },
      {
        icon: "Mic",
        title: "Voice Coaching",
        description: "Practice your pitch with AI and get real-time feedback on delivery.",
      },
      {
        icon: "Users",
        title: "Expert Matching",
        description: "Connect with investors who understand your market.",
      },
      {
        icon: "Shield",
        title: "Investor Ready Score",
        description: "Know exactly where you stand before you pitch.",
      },
    ],
    howItWorks: [
      {
        step: "1",
        title: "Submit Your Pitch",
        description: "Upload your deck and tell us about your business.",
      },
      {
        step: "2",
        title: "Get AI Coaching",
        description: "Receive detailed analysis and improvement recommendations.",
      },
      {
        step: "3",
        title: "Practice & Improve",
        description: "Use voice coaching to perfect your delivery.",
      },
      {
        step: "4",
        title: "Connect",
        description: "When ready, get introduced to aligned investors.",
      },
    ],
  },

  // ==========================================================================
  // INVESTMENT THESIS
  // ==========================================================================
  thesis: {
    focusAreas: [],
    sectors: [],
    stages: ["Pre-Seed","Seed","Series A"],
    geographies: ["Global", "Asia-Pacific", "North America", "Europe"],
    ticketSize: {
      min: "$100K",
      max: "$2M",
      sweet: "$500K",
    },
    philosophy: "Corporate AI Solutions provides white-label AI platforms to turn cold pitch emails and calls into qualified deal flow for businesses.",
    idealFounder: "",
    scoringFocus: "growth" as "storytelling" | "impact" | "growth",
    scoringCriteria: [
      { key: "problem_clarity", label: "Problem Clarity", weight: 0.10 },
      { key: "solution_clarity", label: "Solution Clarity", weight: 0.10 },
      { key: "market_opportunity", label: "Market Opportunity", weight: 0.08 },
      { key: "business_model", label: "Business Model", weight: 0.10 },
      { key: "traction", label: "Traction & Validation", weight: 0.08 },
      { key: "team", label: "Team & Execution", weight: 0.08 },
      { key: "financials", label: "Financial Projections", weight: 0.06 },
      { key: "ask_clarity", label: "Ask & Use of Funds", weight: 0.06 },
      { key: "sdg_alignment", label: "SDG Alignment", weight: 0.08 },
      { key: "impact_measurability", label: "Impact Measurability", weight: 0.08 },
      { key: "theory_of_change", label: "Theory of Change", weight: 0.05 },
      { key: "storytelling", label: "Storytelling", weight: 0.05 },
    ],
    welcomeMessages: {
      discovery: "Welcome to Corporate AI Solutions Story Discovery! I'll help you uncover the compelling narrative behind your startup.",
      practice: "Ready to practice your pitch? I'll give you real-time feedback to sharpen your delivery.",
      simulation: "Let's simulate an investor meeting. I'll play different investor types to prepare you.",
    },
  },

  // ==========================================================================
  // COACHING
  // ==========================================================================
  coaching: {
    coachName: "Maya",
    coachPersonality: "friendly and supportive",
    voiceId: "",
    agentId: "",
  },

  // ==========================================================================
  // PLATFORM SETTINGS
  // ==========================================================================
  platform: {
    urlPrefix: "portal",
    adminRole: "portal_admin",
    features: {
      voiceCoaching: true,
      investorMatching: false,
      deckVersioning: true,
      teamMembers: false,
      analytics: true,
      apiAccess: false,
      sdgScoring: false,
      impactMetrics: false,
      blendedReturns: false,
    },
    founderJourney: [
      { id: "upload", label: "Upload Deck", icon: "Upload" },
      { id: "profile", label: "Complete Profile", icon: "User" },
      { id: "discovery", label: "Story Discovery", icon: "MessageSquare" },
      { id: "refine", label: "Refine Materials", icon: "FileEdit" },
      { id: "practice", label: "Practice Pitch", icon: "Mic" },
    ],
    readinessLevels: [
      { key: "not-ready", label: "Not Ready", minScore: 0, color: "red" },
      { key: "needs-work", label: "Needs Work", minScore: 40, color: "orange" },
      { key: "almost-ready", label: "Almost Ready", minScore: 60, color: "yellow" },
      { key: "investor-ready", label: "Investor Ready", minScore: 80, color: "green" },
    ],
    autoReplyTemplate: `
Thank you for submitting your pitch to Corporate AI Solutions!

We've received your deck and our AI coaching system is analyzing it now.
You'll receive your initial feedback within 24 hours.

Best regards,
The Corporate AI Solutions Team
    `,
  },

  // ==========================================================================
  // FOOTER CONTENT
  // ==========================================================================
  footer: {
    description: "Corporate AI Solutions provides white-label AI platforms to turn cold pitch emails and calls into qualified deal flow for businesses.",
    serviceLinks: [
      { label: "For Founders", href: "/signup/founder" },
      { label: "For Investors", href: "/signup/investor" },
      { label: "Pricing", href: "/pricing" },
    ],
    companyLinks: [
      { label: "About", href: "/about" },
      { label: "How It Works", href: "/#how-it-works" },
      { label: "Contact", href: "/contact" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/privacy" },
      { label: "Terms of Service", href: "/terms" },
    ],
    copyright: "© {year} Corporate AI Solutions. All rights reserved.",
  },

  // ==========================================================================
  // LEGAL & COMPLIANCE
  // ==========================================================================
  legal: {
    privacyUrl: "/privacy",
    termsUrl: "/terms",
    copyrightYear: new Date().getFullYear(),
    complianceRegions: ["GDPR", "CCPA"],
  },

  // ==========================================================================
  // EXTERNAL SERVICE IDS
  // ==========================================================================
  services: {
    supabase: {
      projectId: "",
      url: "",
    },
    vercel: {
      projectId: "",
      deploymentUrl: "",
    },
    elevenlabs: {
      agentId: "",
      voiceId: "",
    },
    anthropic: {},
  },
};

// ==========================================================================
// HELPER FUNCTIONS
// ==========================================================================

export const getCompanyName = () => clientConfig.company.name;

export const getAdminName = () =>
  `${clientConfig.admin.firstName} ${clientConfig.admin.lastName}`;

export const getAdminRole = () => clientConfig.platform.adminRole;

export const getUrlPrefix = () => clientConfig.platform.urlPrefix;

export const getCoachName = () => clientConfig.coaching.coachName;

export const getPortalRoute = (path: string) =>
  `/${clientConfig.platform.urlPrefix}${path}`;

export const getThemeColor = (color: keyof typeof clientConfig.theme.colors) =>
  clientConfig.theme.colors[color];

export const replaceTemplateVars = (text: string): string => {
  return text
    .replace(/{company}/g, clientConfig.company.name)
    .replace(/{coach}/g, clientConfig.coaching.coachName)
    .replace(/{year}/g, String(clientConfig.legal.copyrightYear))
    .replace(/{admin}/g, getAdminName())
    .replace(/{email}/g, clientConfig.company.supportEmail);
};

export const isFeatureEnabled = (feature: keyof typeof clientConfig.platform.features) =>
  clientConfig.platform.features[feature];

export const getPlatformType = () => clientConfig.platformType;
export const isServiceProvider = () => clientConfig.platformType === 'founder_service_provider';
export const isImpactInvestor = () => clientConfig.platformType === 'impact_investor';
export const isFamilyOffice = () => clientConfig.platformType === 'family_office';
export const isCommercialInvestor = () => clientConfig.platformType === 'commercial_investor';
export const hasInvestorMatching = () =>
  clientConfig.platform.features.investorMatching && !isServiceProvider();
export const hasSDGScoring = () =>
  isImpactInvestor() && clientConfig.platform.features.sdgScoring;
export const isScreeningMode = () => clientConfig.platformMode === 'screening';
export const isCoachingMode = () => clientConfig.platformMode === 'coaching';

export type ClientConfig = typeof clientConfig;
export default clientConfig;
